### ISSUE TITLE
When moving from Async Route to Async Route, Component doesn't seem to update

### ISSUE THREAD

**Issue by stevenfitzpatrick** [prateekbh/preact-async-route#1]
```
Favourites = () =>
    System.import('./favourites').then(module => module.default);
CreateFavourites = () =>
    System.import('./create-favourite').then(module => module.default);

...

<Router onChange={this.handleRoute}>
   <AsyncRoute path="/favourites" component={this.Favourites} />
   <AsyncRoute path="/create" component={this.CreateFavourites} />
</Router>
```

When I navigate from a non async Route a async route everything seems to work fine, but when navigating from AsyncRoute path to AsyncRoute path the component doesn't seem to update content even though the path in the url has updated.

In the example above, if I navigate from /favourites to /create within the app, the contents from /favourites is still displayed.

Edit : Maybe because the AsyncRoute Component only has **componentDidMount** and in this scenario the Component is already mounted so it doesn't rerender with new content ?

**Comment by prateekbh** [comment]
@stevenfitzpatrick thanks for reporting this. 
This is fixed, covered with test cases and published to NPM
