### ISSUE TITLE
Preact-Router not playing well with 2.0.2 update 

### ISSUE THREAD

**Issue by rubencodes** [prateekbh/preact-async-route#14]
Hello,

I've been using `preact-async-route@2.0.1` successfully for a while now, but ever since updating to `2.0.2`, `preact-router@2.6.0`'s `route()` function seems to not work between `<AsyncRoute />` pages (url will change in address bar, but UI will not change). I can reproduce this simply by switching between 2.0.1 and 2.0.2. 

For example, if I am currently on the '/' page:
- Running `route('/?param=x')` will work successfully. ✅ 
- Running `route('/non-async-route')` will work successfully. ✅ 
- Running `route('/async-route')` will update the address bar url but not the UI. 🚫

**Comment by NekR** [comment]
I see the same issue.

**Comment by prateekbh** [comment]
cool, will take a look

**Comment by prateekbh** [comment]
opened suggestions at #9, feel free to jump

**Comment by studentIvan** [comment]
👍 +1 for this problem

**Comment by prateekbh** [comment]
@studentIvan @NekR @rubencodes i have updated to 2.1.0 with the implementation in #9 PTAL
