### ISSUE TITLE
Could a method to handle loading failures be added?

### ISSUE THREAD

**Issue by vpzomtrrfrt** [prateekbh/preact-async-route#15]
I'd like to be able to render a different component if `getComponent` fails.  Currently, the page visually appears to remain loading forever

**Comment by prateekbh** [comment]
just curious isn't that doable in the getComponent function itself?

**Comment by prateekbh** [comment]
any thoughts @vpzomtrrfrt

**Comment by vpzomtrrfrt** [comment]
Yeah, that's a good point.  I guess I'll just do that
