### ISSUE TITLE
Programmatically pre load next route

### ISSUE THREAD

**Issue by kontrollanten** [prateekbh/preact-async-route#17]
Thanks for a great package (even though I haven't tried it yet)! I'm wondering if there would be possible to add a way to manually pre load next route. Let's say I've an input field which upon submit will route the user to another lazy route. Then it would be nice if I could pre load the next route when the user starts typing. Would this make sense? If, do you have any good idea how this could be implemented? I'm thinking something like

```javascript
import { h, Component } from 'preact';
import preactAsyncRouteLoader from 'preact-async-route-loader';

export default class MySubmitForm extends Component {
  handleInputChange() {
    preactAsyncRouteLoader('/next-path');
  }

  ...
}

**Comment by kontrollanten** [comment]
Sorry, I found that this is a duplicate of #5

**Comment by prateekbh** [comment]
@kontrollanten depending on what packager(webpack/rollup) you use, the way of prefetching the chunks change. 
I'd love to hear if you have any ideas of abstracting it out

**Comment by kontrollanten** [comment]
Wouldn't it be possible to solve it the same way as the AsynRoute loads the component?

App.js
```
export const HomeRoute = <AsyncRoute path="/home" loadComponent={loadHome} />;

export default () => {
  <Router>
    {HomeRoute}
  </Router>
};
```

FarFromHome.js
```
import { HomeRoute } from './App';

export default class FarFromHome extends Component {
  handleFocusMenu() {
    HomeRoute.loadComponent();
  }

...
}
```

**Comment by developit** [comment]
^ that's actually a pretty neat technique and we could probably have preact-router do the getComponent call..

**Comment by kontrollanten** [comment]
I'd guess the ideal solution would be to add prefetch `<link>` tag to the head, so the browser can prioritize the fetching. But this works.

What I ended up with was 

App.js
```
export const loadHome = () =>
  import('./home')
    .then(module => module.default);

export default () => {
  <Router>
    <AsyncRoute path="/home" loadComponent={loadHome} />
  </Router>
};
```
FarFromHome.js
```
import { loadHome as prefetchHome } from './App';

export default class FarFromHome extends Component {
  handleFocusMenu() {
    prefetchHome();
  }

...
}
```

**Comment by prateekbh** [comment]
Now that I have some free cycles, I am open to take a deeper look.

Quick question: most chunk of work for preloading is just 
```
export const loadHome = () =>
  import('./home')
    .then(module => module.default);
```

and calling ☝️ anytime you want to preload. So I am not fully clear what can be a part of the package `preact-async-route`/`preact-router`. 

But in case you have a solid outline, would be happy to include

**Comment by kontrollanten** [comment]
I agree. I can't really see that it would be a part of the `preact-async-route / preact-router` API (as long as we don't find a way of creating a `<link>` tag), but it could be nice to display it as an example.

**Comment by prateekbh** [comment]
@developit any thoughts?

**Comment by prateekbh** [comment]
Here: the proper solution finally.

https://medium.com/webpack/link-rel-prefetch-preload-in-webpack-51a52358f84c
