### ISSUE TITLE
Pass props to lazy loaded component

### ISSUE THREAD

**Issue by dackom** [prateekbh/preact-async-route#19]
I've been trying to pass props to component that is lazy loaded, but I had no luck. Can someone, please, give example how to this?

`const loadMyComponent = () => {return System.import('./component').then((component) => component.default)};`

`<AsyncRoute path="/route" getComponent={loadMyComponent} />`

In normal router I would just add account={this.state.account}, and it was passed to component. But this obviously doesn't work here. How to achieve this with AsyncRoute?

**Comment by prateekbh** [comment]
so https://github.com/prateekbh/preact-async-route/blob/master/src/index.js#L58

should be passing any props passed to `AsyncRoute` to to the component down below and also there is this test: https://github.com/prateekbh/preact-async-route/blob/master/tests/index.js#L81.

So I am curious ho, are you passing props directly to `AsyncRoute` of `preact-router`?

**Comment by dackom** [comment]
Yes, you are right. It works as it should work. My mistake, it was late night. :) 

Thank you, you can delete the thread.
