### ISSUE TITLE
calling a route for initial load

### ISSUE THREAD

**Issue by tschnoelzer** [prateekbh/preact-async-route#20]
Hi Team,

when requesting a route in the browser address bar like localhost:8080/home which is a `<AsyncRoute path='/home/:?' getComponent={getHome} />` it works in npm run dev but throwing an error when called after build by http-server:

>  Cannot GET /home

all working fine when requesting home via link from the index page.

what am I missing?

**Comment by prateekbh** [comment]
So `AsyncRoute` is a client side routing solution, which means if you land on `/` and try to navigate to `/home` /profile` etc it'll do the routing for you. But if server directly gets hit for any of those routes, there should be an html served for all those location from the server.

So please check that the same html is served for `/home` as well from the server

**Comment by tschnoelzer** [comment]
Thx alot @prateekbh ! I just found my problem in firebase hosting rewrite config where I had public folder duplicated under destination of rewrite ... so there was no base page found ... now reimplementing my app again as I reduced to minimum ... lets see ... thx again!
