### ISSUE TITLE
maybe release next version?

### ISSUE THREAD

**Issue by studentIvan** [prateekbh/preact-async-route#23]
Now we have to use git master branch in package.json :)

**Comment by prateekbh** [comment]
Didnt get you. can you please explain in detail?

**Comment by studentIvan** [comment]
@prateekbh look at here https://github.com/prateekbh/preact-async-route/releases
and look at here https://github.com/prateekbh/preact-async-route/blob/master/package.json#L3

**Comment by studentIvan** [comment]
@prateekbh sorry, I have wrote some nonsense
