### ISSUE TITLE
There should be a way to pass custom props to <AsyncRoute /> 

### ISSUE THREAD

**Issue by minaseem** [prateekbh/preact-async-route#24]

**Comment by prateekbh** [comment]
An example would be super helpful 👍

**Comment by prateekbh** [comment]
Also see #19

**Comment by minaseem** [comment]
Thanks for the reference.
I see that we can pass the props,  it is working. But throwing a typescript error.

On doing
```jsx
<AsyncRoute path={x} name="Foo" getComponent={getComponent} name="Foo" />
```
below typescript error is thrown 

`Error:(39, 99) TS2339: Property 'name' does not exist on type 'Readonly<IAsyncRouteProps & Attributes & { children?: ComponentChild[]; ref?: Ref<any>; }>'.`

**Comment by prateekbh** [comment]
Ouch TS!!!! I can definitely use some help there

**Comment by minaseem** [comment]
Please review https://github.com/prateekbh/preact-async-route/pull/25
