### ISSUE TITLE
Is this package obsolete?

### ISSUE THREAD

**Issue by ChrisBrownie55** [prateekbh/preact-async-route#28]
It would appear that this package does code-splitting but now, according to the preact-cli readme, code splitting is built into the react router, or in their words:

> Fully automatic code splitting for routes

And even without the built-in code splitting, they also let you:

> Transparently code-split any component with an `async!` prefix

**Comment by prateekbh** [comment]
for preact-cli code-splitting is done automatically, but not if you're not using preact-cli..

also even with preact-cli there is no way to give a loader component as it is with this package, so it has some use even there.
