### ISSUE TITLE
The props has not ben passed

### ISSUE THREAD

**Issue by wulunyi** [prateekbh/preact-async-route#3]
<AsyncRoute 
path="/chat/:id"
uid={uid}
suid={suid}
info={info}
component={getChat} />

**Comment by prateekbh** [comment]
Do you mean props has not been passed to the component?
Also can you please give a small code sample to test against?

**Comment by sxcooler** [comment]
I guess he/she means that in preact-router, props directly send to render() like render({foo}, {bar}) {...}.
nowadays async-route do not do this.

**Comment by prateekbh** [comment]
yeah, that goes to preact-router side. but for now even the component function doesnt get props.
will fix this and publish a version.

**Comment by prateekbh** [comment]
so i pass the preact-router standard props 
https://github.com/prateekbh/preact-async-route/blob/master/src/index.js#L44

let me know if you think we should pass al of them as it is..

**Comment by sxcooler** [comment]
@prateekbh after a few days practicing, I suggest that pass them all. (to keep consistent with preact-router)

**Comment by prateekbh** [comment]
@sxcooler happy to do so. ca you provide me a little context on what exactly is the need that you are trying to fulfill.
I see that even normal components in preact-router are also getting only these 2 props i.e. url and matches

https://github.com/developit/preact-router/blob/master/src/index.js#L219

**Comment by prateekbh** [comment]
ahhh i get it...
fixed and published

**Comment by sxcooler** [comment]
Thank you & sorry about out of touch, I've been with my family this weekend.
