### ISSUE TITLE
the example doesn't work

### ISSUE THREAD

**Issue by sxcooler** [prateekbh/preact-async-route#8]
I put the example into an Apache server, and it doesn't work, the app.js load successfully, but page is blank and console shows no error.
Then I run "npm install" & rebuild example with webpack, it still doesn't work.
My environment: Mac OS 10.12.5, Chrome 59.0.3071.115.

**Comment by prateekbh** [comment]
hi!
apologies for the bug in example, I seemed to miss updating the example. you can pull and try now

**Comment by sxcooler** [comment]
Thank you for your reply, it works now, but I've found another interesting point: 
in this demo, if I click some link, the router works well. But if I enter the same url directly, it returns 404 not found.
Is it by design or a bug?

**Comment by sxcooler** [comment]
Thank you for your reply, it works now!
