### ISSUE TITLE
Any way to avoid multiple mounts?

### ISSUE THREAD

**Issue by rubencodes** [prateekbh/preact-async-route#9]
I have a router setup in the following style:

```
const loadHome = () => import('/home').then((component) => component.default);
const App = () => (
	<div id="app">
		<Header />
		<Router>
			<AsyncRoute path="/" getComponent={loadHome} />
			<AsyncRoute path="/:pathOne" getComponent={loadHome} />
			<AsyncRoute path="/:pathOne/:pathTwo" getComponent={loadHome} />
		</Router>
	</div>
);
export default App;
```

**What's Happening**
What I'm seeing is whenever there is navigation between these routes that share a component, the Home component unmounts then remounts. This triggers unnecessary data reloads in my app, which I would like to avoid.

**What's Expected**
When I navigate between the routes *without* using AsyncRoute, the transition is seamless, without these unnecessary mounts/unmounts. 

Is there any way to avoid these unmounts/remounts between paths that load the same component?

**Comment by prateekbh** [comment]
just in case we go with two, possible regex to be used: `/\/?\:[a-z]*/g`

**Comment by prateekbh** [comment]
releasing a version with option1, to minimise any further problems. But the issue is open for further discussions
